/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App
{
    public String getGreeting() {
        return "Hello";
    }
    public static void main(String[] args)
    {
       ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);

        ProductProvider provider = context.getBean(ProductProvider.class);
        Renderer renderer = context.getBean(Renderer.class);
        renderer.render(provider.getProducts());

        CategoryRequest request = context.getBean(CategoryRequest.class);
        request.execute();
    }
}